### ISSUE TITLE
is there RDMA test of Alveo FPGA with Mellanox card ?

### ISSUE THREAD

**Issue by torukskywalker** [Xilinx/RecoNIC#14]

**Comment by zhguanw-amd** [comment]
We are currently working on rdma-core support, which can enable RecoNIC to communicate with RDMA NICs from other vendors.

**Comment by torukskywalker** [comment]
Then what is the schedule?

**Comment by zhguanw-amd** [comment]
We don't have fixed timeline for it

**Comment by wtao0221** [comment]
So, is this feature supported now?
