### ISSUE TITLE
PATCH not apply after running ./gen_base_nic.sh

### ISSUE THREAD

**Issue by jiandongg** [Xilinx/RecoNIC#18]
PATCH not apply after running ./gen_base_nic.sh.
the source files don't change at all.

**Comment by zhguanw-amd** [comment]
Please read the README.md carefully and do it step by step.

**Comment by jiandongg** [comment]
![截屏2024-03-16 16 10 23](https://github.com/Xilinx/RecoNIC/assets/38243279/a9b7ed8a-7941-40fe-b026-5ab43d5c9b0f)
![截屏2024-03-16 16 11 35](https://github.com/Xilinx/RecoNIC/assets/38243279/6af9870a-2e42-467a-ae91-82d82e890abd)


> Please read the README.md carefully and do it step by step.

**Comment by jiandongg** [comment]
MY FAULT.

TO ALL RECONIC USER,
if you want to change card, like using au200 but not au280. YOU SHOULD NOT use  qdma_no_sriov_au200.tcl.
EVEN  qdma_no_sriov_au250.tcl is changed by PATCH, but it is not correct totally. 
YOU SHOULD modify  qdma_no_sriov_au200.tcl mannualy, according to qdma_no_sriov_au280.tcl or qdma_no_sriov_au250.tcl.

THANKS!


Related comment by developer in other issue:

Hi Qianyi,

You are using the default qdma_no_sriov_au280.tcl located at base_nics/open-nic-shell/src/qdma_subsystem/vivado_ip, which is not right. The default one doesn't support QDMA AXI-MM channel and PCIe slave bridge, that's why you can't see those ports. It's not the right way, if you simply remove those ports. You can copy qdma_no_sriov_au250.tcl, rename it as au280 and change CONFIG.xlnx_ref_board {AU250} to AU280 in this file. It should solve this issue.

Thanks,
Guanwen
