### ISSUE TITLE
Is there a roadmap for RecoNIC support ERNICv4.0?

### ISSUE THREAD

**Issue by jiandongg** [Xilinx/RecoNIC#23]
Thanks for your team's excellent work.
I want to know is there a roadmap for RecoNIC support ERNIC v4.0? Could be in this year or the next year? thanks

**Comment by zhguanw-amd** [comment]
@jiandongg 

Hi Jiandong,

To support ERNIC v4.0, we need to upgrade Vivado to above 2022.2 version. With newer Vivado versions, we have to upgrade QDMA from 4.0 to 5.0 as well. And we might also need to upgrade the driver related to QDMA. At the moment, we have the support for ERNIC v4.0 and its register space in the internal version. But we still don't have the bandwidth for upgrading QDMA yet. Once we have these things ready, we will push to this public repository. Probably by the end of this year, depending on my priorities/projects.
