### ISSUE TITLE
ERROR: [Coretcl 2-1134] No IP matching VLNV 'xilinx.com:ip:vitis_net_p4:1.0' was found. Please check your repository configuration.

### ISSUE THREAD

**Issue by qgzln** [Xilinx/RecoNIC#29]
I install vitis_net_p4
![image](https://github.com/user-attachments/assets/7f869a4d-7463-40fe-a205-403b1529c9e0)

**Comment by zhguanw-amd** [comment]
@qgzln 

Hi,

Could you try using the standard Vitis Networking P4 example to see if it has the same issue? This problem seems related to the Vivado tool installation. It might be helpful to contact your FAE for more information.

**Comment by zhguanw-amd** [comment]
Close this thread due to inactivity. Feel free to reopen it if you have further questions.
