### ISSUE TITLE
can i remove packet_parser.p4 when i run rdma test?

### ISSUE THREAD

**Issue by qgzln** [Xilinx/RecoNIC#31]
In the pacekt_filter.v, I add logic that distinguishes between RDAM and non-RDMA network packets。
so can i run rdma test?

**Comment by zhguanw-amd** [comment]
@qgzln Yes, it will work. You can use the same simulation in RecoNIC to test your code first before doing on-board testing.

**Comment by qgzln** [comment]
> @qgzln Yes, it will work. You can use the same simulation in RecoNIC to test your code first before doing on-board testing.

@zhguanw-amd Thanks, do I still need to modify the software part of Reconic? If so, could you tell me which software needs to be modified?

**Comment by zhguanw-amd** [comment]
@qgzln no need to modify any software code.
